repos:
  - repo: local
    hooks:
      - id: run-format
        name: Run pnpm format:fix
        entry: pnpm
        args: ["run", "format:fix"]
        language: node
        pass_filenames: false
